# Packages

```{r}
#install.packages('runjags')
library(tidyverse)
library(ggplot2)
library(dplyr)
library(plyr)
library(MASS)
library(Matrix)
source('Functions.R')
```

# Data

```{r}
#raw_23_24 = read.csv('EPL_2023_2024.csv')
raw_22_23 = read.csv('EFL_22_23.csv')
raw_21_22 = read.csv('EFL_21_22.csv')
raw_20_21 = read.csv('EFL_20_21.csv')
raw_19_20 = read.csv('EFL_19_20.csv')
#raw_18_19 = read.csv('La Liga data/LL_18_19.csv')
#raw_17_18 = read.csv('EPL_2017_2018.csv')

features = c('Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG',
             'AvgH', 'AvgD', 'AvgA', 'AvgCH', 'AvgCD', 'AvgCA',
             'AvgC.2.5', 'AvgC.2.5.1')

#sub_23_24 = raw_23_24[1:380, features]
sub_22_23 = raw_22_23[1:380, features]
sub_21_22 = raw_21_22[1:380, features]
sub_20_21 = raw_20_21[1:380, features]
sub_19_20 = raw_19_20[1:380, features]
#sub_18_19 = raw_18_19[1:380, features]
```

# New Functions

```{r}
ou_odds_to_prob = function(ou_odds, normalize=TRUE){
  
  stopifnot(all(ou_odds >= 1, na.rm=TRUE))
  
  if (!is.matrix(ou_odds)){
    
    if ('data.frame' %in% class(ou_odds)){
      ou_odds = as.matrix(ou_odds)
    } else {
      ou_odds = matrix(ou_odds, nrow=1,
                    dimnames = list(NULL, names(ou_odds)))
    }
  }
  
  # Prepare the list that will be returned.
  out = vector(mode='list', length=2)
  names(out) = c('probabilities', 'margin')
  
  # Some useful quantities
  n_odds = nrow(ou_odds)
  n_outcomes = ncol(ou_odds)
  
  # Inverted odds and margins
  inverted_odds = 1 / ou_odds
  inverted_odds_sum = rowSums(inverted_odds)
  out$margin = inverted_odds_sum - 1

  out$probabilities = inverted_odds / inverted_odds_sum
    
  ## do a final normalization to make sure the probabilities sum to 1 without rounding errors.
  if (normalize){
    out$probabilities = (1 * out$probabilities) / rowSums(out$probabilities)
  }
  
  return(out)
}
```

```{r}
odds_to_prob = function(odds, normalize=TRUE){
  
  stopifnot(all(odds >= 1, na.rm=TRUE))
  
  if (!is.matrix(odds)){
    
    if ('data.frame' %in% class(odds)){
      odds = as.matrix(odds)
    } else {
      odds = matrix(odds, nrow=1,
                    dimnames = list(NULL, names(odds)))
    }
  }
  
  # Prepare the list that will be returned.
  out = vector(mode='list', length=2)
  names(out) = c('probabilities', 'margin')
  
  # Some useful quantities
  n_odds = nrow(odds)
  n_outcomes = ncol(odds)
  
  # Inverted odds and margins
  inverted_odds = 1 / odds
  inverted_odds_sum = rowSums(inverted_odds)
  out$margin = inverted_odds_sum - 1

  out$probabilities = inverted_odds / inverted_odds_sum
    
  ## do a final normalization to make sure the probabilities sum to 1 without rounding errors.
  if (normalize){
    out$probabilities = (1 * out$probabilities) / rowSums(out$probabilities)
  }
  
  # Make sure the matrix of implied probabilities has column names.
  if (!is.null(colnames(odds))){
    colnames(out$probabilities) = colnames(odds)
  }
  
  # check if there are any probabilities outside the 0-1 range.
  problematic = apply(out$probabilities, MARGIN = 1, FUN=function(x){any(x > 1 | x < 0)})
  problematic[is.na(problematic)] = TRUE
  
  if (any(problematic, na.rm=TRUE)){
    warning(sprintf('Probabilities outside the 0-1 range produced at %d instances.\n',
                    sum(problematic)))
  }
  
  out$problematic = problematic
  
  return(out)
}
```

```{r}
ou_prob = ou_odds_to_prob(raw_19_20[, c('AvgC.2.5', 'AvgC.2.5.1')])$probabilities
hda_prob = odds_to_prob(raw_19_20[, c('AvgCH', 'AvgCD', 'AvgCA')])$probabilities

mis_prob = cbind(hda_prob, ou_prob)
head(mis_prob)
```

```{r}
mis_prob_sq_error = function(pars, trgt_probs){
  
  pars = exp(pars) # trick to avoid negative lambda parameters.
  hda_ou_probs = numeric(5)
  probmat = stats::dpois(0:49, lambda=pars[1]) %o% stats::dpois(0:49, lambda=pars[2])
  
  #1x2
  hda_ou_probs[2] = sum(diag(probmat))
  hda_ou_probs[1] = sum(probmat[lower.tri(probmat)])
  hda_ou_probs[3] = 1 - sum(hda_ou_probs[1:2])
  
  #ou
  total_goals = matrix(NA, nrow = 50, ncol = 50)
  
  for (i in 1:50){
    for (j in 1:50){
      total_goals[i, j] = (i-1) + (j-1)
    }
  }
  
  hda_ou_probs[4] = sum(probmat[total_goals > 2.5])
  hda_ou_probs[5] = sum(probmat[total_goals < 2.5])
  
  sum((hda_ou_probs - trgt_probs)^2)
  
}
```

```{r}
mis_prob_to_expg = function(probabilities){
  
  # Convert to matrix
  if (!is.matrix(probabilities)){
    if (is.numeric(probabilities)){
      probabilities = matrix(probabilities, nrow=1,
                              dimnames = list(NULL, names(probabilities)))
    } else {
      probabilities = as.matrix(probabilities)
    }
    
    
  }
  
  stopifnot(ncol(probabilities) == 5,
            all(abs(rowSums(probabilities) - 1 - 1) < 0.0001))
  
  expg = matrix(ncol=2, nrow=nrow(probabilities))
  sq_errors = numeric(nrow(probabilities))
  
  for (i in 1:nrow(probabilities)){
    
    optim_res = stats::optim(c(0,0), fn=mis_prob_sq_error,
                              trgt_prob=probabilities[i,])
    
    expg[i,] = exp(optim_res$par)
    sq_errors[i] = optim_res$value
    
  }
  
  out = list(expg = expg, sq_errors=sq_errors)
  
  return(out)
}
```

# Some preparations

```{r}
## last season
last_season = sub_21_22

## hda and ou
last_season_hda_prob = odds_to_prob(last_season[, c('AvgCH', 'AvgCD', 'AvgCA')])$probabilities
last_season_ou_prob = ou_odds_to_prob(last_season[, c('AvgC.2.5', 'AvgC.2.5.1')])$probabilities

last_season_hdaou_prob = cbind(last_season_hda_prob, last_season_ou_prob)
last_season_hdaou_expg = mis_prob_to_expg(last_season_hdaou_prob)

last_season$hdaou_xhg = last_season_hdaou_expg$expg[, 1]
last_season$hdaou_xag = last_season_hdaou_expg$expg[, 2]

## hda
last_season_hda_expg = prob_to_expg(last_season_hda_prob)

last_season$hda_xhg = last_season_hda_expg$expg[, 1]
last_season$hda_xag = last_season_hda_expg$expg[, 2]

## current season
current_season = sub_22_23

## hda and ou
current_season_hda_prob = odds_to_prob(current_season[, c('AvgCH', 'AvgCD', 'AvgCA')])$probabilities
current_season_ou_prob = ou_odds_to_prob(current_season[, c('AvgC.2.5', 'AvgC.2.5.1')])$probabilities

current_season_hdaou_prob = cbind(current_season_hda_prob, current_season_ou_prob)
current_season_hdaou_expg = mis_prob_to_expg(current_season_hdaou_prob)

current_season$hdaou_xhg = current_season_hdaou_expg$expg[, 1]
current_season$hdaou_xag = current_season_hdaou_expg$expg[, 2]

## hda
current_season_hda_expg = prob_to_expg(current_season_hda_prob)

current_season$hda_xhg = current_season_hda_expg$expg[, 1]
current_season$hda_xag = current_season_hda_expg$expg[, 2]
```

```{r}
current_season_teams = unique(current_season$HomeTeam)
last_season_teams = unique(last_season$HomeTeam)
```

```{r}
new_teams = current_season_teams[!(current_season_teams %in% last_season_teams)]
dropped_teams = last_season_teams[!(last_season_teams %in% current_season_teams)] 
```

```{r}
replaced_last_season = last_season

for (i in 1:length(new_teams)){
  
  replaced_last_season$HomeTeam[replaced_last_season$HomeTeam == dropped_teams[i]] = new_teams[i]
  replaced_last_season$AwayTeam[replaced_last_season$AwayTeam == dropped_teams[i]] = new_teams[i]
  
}

replaced_last_season_teams = unique(replaced_last_season$HomeTeam)
#unique(current_season$HomeTeam)
```

```{r}
current_season$HomeTeam[!(current_season$HomeTeam %in% replaced_last_season_teams)]
```

# Modelling

## The first 50s

```{r}
first_preds = current_season[1:50, ]

first_preds$hda_expg1 = rep(NA, 50)
first_preds$hda_expg2 = rep(NA, 50)

first_preds$hdaou_expg1 = rep(NA, 50)
first_preds$hdaou_expg2 = rep(NA, 50)

new_train_set = replaced_last_season

##hda
for (i in 1:5){
  
  #i = 1
  replaced_model = expg_model(goals1 = round(new_train_set$hda_xhg), goals2 = round(new_train_set$hda_xag),
                              team1 = new_train_set$HomeTeam, team2 = new_train_set$AwayTeam,
                              model = 'gaussian')
  lower_bound = 1 + (i-1)*10
  upper_bound = i*10
    
  new_match_day = current_season[lower_bound:upper_bound, ]
  
  pred = pred_expg(replaced_model, return_df = T,
                      team1 = current_season$HomeTeam[lower_bound:upper_bound], 
                      team2 = current_season$AwayTeam[lower_bound:upper_bound])
  
  first_preds$hda_expg1[lower_bound:upper_bound] = pred$expg1
  first_preds$hda_expg2[lower_bound:upper_bound] = pred$expg2
  
  new_train_set = rbind(new_train_set, new_match_day) 
  
}

## hda and ou
for (i in 1:5){
  
  #i = 1
  replaced_model = expg_model(goals1 = round(new_train_set$hdaou_xhg), goals2 = round(new_train_set$hdaou_xag),
                              team1 = new_train_set$HomeTeam, team2 = new_train_set$AwayTeam,
                              model = 'gaussian')
  lower_bound = 1 + (i-1)*10
  upper_bound = i*10
    
  new_match_day = current_season[lower_bound:upper_bound, ]
  
  pred = pred_expg(replaced_model, return_df = T,
                      team1 = current_season$HomeTeam[lower_bound:upper_bound], 
                      team2 = current_season$AwayTeam[lower_bound:upper_bound])
  
  first_preds$hdaou_expg1[lower_bound:upper_bound] = pred$expg1
  first_preds$hdaou_expg2[lower_bound:upper_bound] = pred$expg2
  
  new_train_set = rbind(new_train_set, new_match_day) 
  
}
```

## The rest

```{r}
pred = current_season

pred$hda_expg1 = rep(NA, 380)
pred$hda_expg2 = rep(NA, 380)

pred$hdaou_expg1 = rep(NA, 380)
pred$hdaou_expg2 = rep(NA, 380)

played_matches = 50
new_train_set = current_season[1:played_matches, ]

## hda
for (i in 1:33){
  
  model_xg = expg_model(goals1 = round(new_train_set$hda_xhg), goals2 = round(new_train_set$hda_xag),
                        team1 = new_train_set$HomeTeam, team2 = new_train_set$AwayTeam, model = 'gaussian')
  
  lower_bound = played_matches + 1 + (i-1)*10
  upper_bound = played_matches + i*10
    
  new_match_day = current_season[lower_bound:upper_bound, ]
  
  pred_xg = pred_expg(model_xg, return_df = T,
                      team1 = new_match_day$HomeTeam, 
                      team2 = new_match_day$AwayTeam)
  
  pred$hda_expg1[lower_bound:upper_bound] = pred_xg$expg1
  pred$hda_expg2[lower_bound:upper_bound] = pred_xg$expg2
  
  new_train_set = rbind(new_train_set, new_match_day)
  
}

## hda and ou
for (i in 1:33){
  
  model_xg = expg_model(goals1 = new_train_set$hdaou_xhg, goals2 = new_train_set$hdaou_xag,
                        team1 = new_train_set$HomeTeam, team2 = new_train_set$AwayTeam, model = 'gaussian')
  
  lower_bound = played_matches + 1 + (i-1)*10
  upper_bound = played_matches + i*10
    
  new_match_day = current_season[lower_bound:upper_bound, ]
  
  pred_xg = pred_expg(model_xg, return_df = T,
                      team1 = new_match_day$HomeTeam, 
                      team2 = new_match_day$AwayTeam)
  
  pred$hdaou_expg1[lower_bound:upper_bound] = pred_xg$expg1
  pred$hdaou_expg2[lower_bound:upper_bound] = pred_xg$expg2
  
  new_train_set = rbind(new_train_set, new_match_day)
  
}
```

```{r}
pred$hda_expg1[1:50] = first_preds$hda_expg1
pred$hda_expg2[1:50] = first_preds$hda_expg2

pred$hdaou_expg1[1:50] = first_preds$hdaou_expg1
pred$hdaou_expg2[1:50] = first_preds$hdaou_expg2
```

```{r}
## market
mar_hda_ge_error = abs(pred$hda_xhg + pred$hda_xag - pred$FTHG - pred$FTAG)
mar_hda_sup_error = abs(pred$hda_xhg - pred$hda_xag - pred$FTHG + pred$FTAG)

mar_hdaou_ge_error = abs(pred$hdaou_xhg + pred$hdaou_xag - pred$FTHG - pred$FTAG)
mar_hdaou_sup_error = abs(pred$hdaou_xhg - pred$hdaou_xag - pred$FTHG + pred$FTAG)

## and us
mod_hda_ge_error = abs(pred$hda_expg1 + pred$hda_expg2 - pred$FTHG - pred$FTAG)
mod_hda_sup_error = abs(pred$hda_expg1 - pred$hda_expg2 - pred$FTHG + pred$FTAG)

mod_hdaou_ge_error = abs(pred$hdaou_expg1 + pred$hdaou_expg2 - pred$FTHG - pred$FTAG)
mod_hdaou_sup_error = abs(pred$hdaou_expg1 - pred$hdaou_expg2 - pred$FTHG + pred$FTAG)
```

```{r}
plot(cummean(mar_hda_ge_error), type = 'l', col = 'red', ylim = c(0.9, 1.8),
     xlab = 'EFL 2021_2022', ylab = 'EFL GE error')
lines(cummean(mar_hdaou_ge_error), type = 'l', col = 'black')
lines(cummean(mod_hda_ge_error), type = 'l', col = 'green')
lines(cummean(mod_hdaou_ge_error), type = 'l', col = 'blue')

size = par(cex = 0.8)
legend(250, 1.6, legend=c("1X2 Market", "1X2 and OU Market", "1X2 Model", "1X2 and OU Model"),
       col=c("red", "black", 'green', 'blue'), lty = 1)

plot(cummean(mar_hda_sup_error), type = 'l', col = 'red', ylim = c(0.7, 1.4),
     xlab = 'EFL 2021_2022', ylab = 'EFL SUP error')
lines(cummean(mar_hdaou_sup_error), type = 'l', col = 'black')
lines(cummean(mod_hda_sup_error), type = 'l', col = 'green')
lines(cummean(mod_hdaou_sup_error), type = 'l', col = 'blue')

size = par(cex = 0.8)
legend(250, 1.0, legend=c("1X2 Market", "1X2 and OU Market", "1X2 Model", "1X2 and OU Model"),
       col=c("red", "black", 'green', 'blue'), lty = 1)
```



# Draft

```{r}
mean(mar_hda_ge_error)
mean(mod_hda_ge_error)

mean(mar_hda_sup_error)
mean(mod_hda_sup_error)
```

```{r}
mean(mar_hdaou_ge_error)
mean(mod_hdaou_ge_error)

mean(mar_hdaou_sup_error)
mean(mod_hdaou_sup_error)
```

